name: bumpAgentConfig
description: Create new config version and notify connected agents
inputs:
  - name: org_id
    type: integer
  - name: changes
    type: object
output:
  type: object
steps:
  - id: execute
    action: return
    value:
      ok: true
