name: teardownDeployment
description: Stop and clean up a deployment instance
inputs:
  - name: deployment_id
    type: integer
output:
  type: object
steps:
  - id: execute
    action: return
    value:
      ok: true
